name: Deploy

on:
  push:
    tags:
    - v*

jobs:

  deploy-build:
    name: Deploy (*)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
    - name: Export
      run: |
        ~/.local/bin/conan create . conan-iceshard-tools/0.6.2@iceshard/stable
    - name: Deploy
      run: |
        ~/.local/bin/conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        ~/.local/bin/conan upload -r conan-iceshard conan-iceshard-tools/0.6.2@iceshard/stable --all
